//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ServiceReferenceRepartidor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SLWCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BL.Repartidor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BL.UnidadEntrega))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BL.EstatusUnidad))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BL.Usuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BL.Rol))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRepartidor.IRepartidor")]
    public interface IRepartidor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/GetAll", ReplyAction="http://tempuri.org/IRepartidor/GetAllResponse")]
        PL.ServiceReferenceRepartidor.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/GetAll", ReplyAction="http://tempuri.org/IRepartidor/GetAllResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/UnidadEntregaGetAll", ReplyAction="http://tempuri.org/IRepartidor/UnidadEntregaGetAllResponse")]
        PL.ServiceReferenceRepartidor.Result UnidadEntregaGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/UnidadEntregaGetAll", ReplyAction="http://tempuri.org/IRepartidor/UnidadEntregaGetAllResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> UnidadEntregaGetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/UsuarioGetAll", ReplyAction="http://tempuri.org/IRepartidor/UsuarioGetAllResponse")]
        PL.ServiceReferenceRepartidor.Result UsuarioGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/UsuarioGetAll", ReplyAction="http://tempuri.org/IRepartidor/UsuarioGetAllResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> UsuarioGetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/GetById", ReplyAction="http://tempuri.org/IRepartidor/GetByIdResponse")]
        PL.ServiceReferenceRepartidor.Result GetById(int IdRepartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/GetById", ReplyAction="http://tempuri.org/IRepartidor/GetByIdResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> GetByIdAsync(int IdRepartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Add", ReplyAction="http://tempuri.org/IRepartidor/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReferenceRepartidor.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BL.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BL.EstatusUnidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BL.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BL.Rol))]
        PL.ServiceReferenceRepartidor.Result Add(BL.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Add", ReplyAction="http://tempuri.org/IRepartidor/AddResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> AddAsync(BL.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Update", ReplyAction="http://tempuri.org/IRepartidor/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReferenceRepartidor.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BL.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BL.EstatusUnidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BL.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BL.Rol))]
        PL.ServiceReferenceRepartidor.Result Update(BL.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Update", ReplyAction="http://tempuri.org/IRepartidor/UpdateResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> UpdateAsync(BL.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Delete", ReplyAction="http://tempuri.org/IRepartidor/DeleteResponse")]
        PL.ServiceReferenceRepartidor.Result Delete(int IdRepartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Delete", ReplyAction="http://tempuri.org/IRepartidor/DeleteResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> DeleteAsync(int IdRepartidor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepartidorChannel : PL.ServiceReferenceRepartidor.IRepartidor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepartidorClient : System.ServiceModel.ClientBase<PL.ServiceReferenceRepartidor.IRepartidor>, PL.ServiceReferenceRepartidor.IRepartidor {
        
        public RepartidorClient() {
        }
        
        public RepartidorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepartidorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepartidorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepartidorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL.ServiceReferenceRepartidor.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public PL.ServiceReferenceRepartidor.Result UnidadEntregaGetAll() {
            return base.Channel.UnidadEntregaGetAll();
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> UnidadEntregaGetAllAsync() {
            return base.Channel.UnidadEntregaGetAllAsync();
        }
        
        public PL.ServiceReferenceRepartidor.Result UsuarioGetAll() {
            return base.Channel.UsuarioGetAll();
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> UsuarioGetAllAsync() {
            return base.Channel.UsuarioGetAllAsync();
        }
        
        public PL.ServiceReferenceRepartidor.Result GetById(int IdRepartidor) {
            return base.Channel.GetById(IdRepartidor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> GetByIdAsync(int IdRepartidor) {
            return base.Channel.GetByIdAsync(IdRepartidor);
        }
        
        public PL.ServiceReferenceRepartidor.Result Add(BL.Repartidor repartidor) {
            return base.Channel.Add(repartidor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> AddAsync(BL.Repartidor repartidor) {
            return base.Channel.AddAsync(repartidor);
        }
        
        public PL.ServiceReferenceRepartidor.Result Update(BL.Repartidor repartidor) {
            return base.Channel.Update(repartidor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> UpdateAsync(BL.Repartidor repartidor) {
            return base.Channel.UpdateAsync(repartidor);
        }
        
        public PL.ServiceReferenceRepartidor.Result Delete(int IdRepartidor) {
            return base.Channel.Delete(IdRepartidor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceRepartidor.Result> DeleteAsync(int IdRepartidor) {
            return base.Channel.DeleteAsync(IdRepartidor);
        }
    }
}
