//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrega
    {
        public int IdEntrega { get; set; }
        public Nullable<int> IdPaquete { get; set; }
        public Nullable<int> IdRepartidor { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<int> IdEstatusEntrega { get; set; }
    
        public virtual EstatusEntrega EstatusEntrega { get; set; }
        public virtual Paquete Paquete { get; set; }
        public virtual Repartidor Repartidor { get; set; }
    }
}
